### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by mertyirmibes** [mertyirmibes/n#1]
#reverse encryption 

def reverse(word):
    return word[::-1]
while True:
    sentence = input("Enter word (type 'stop' to exit): ")
    if sentence.lower() == 'stop':  
        print("End.")
        break
    print(reverse(sentence))

**Comment by advait-zx** [comment]
i can work on this please specify details

**Comment by PrathamjyotSingh** [comment]
**code is correct but correct indentation is:**

def reverse(word):
    return word[::-1]

while True:
    sentence = input("Enter word (type 'stop' to exit): ")
    if sentence.lower() == 'stop':
        print("End.")
        break
    print(reverse(sentence))

**Comment by Nandini1071** [comment]
Hi @mertyirmibes, is this issue still open, if yes then what is the requirement would like to contribute on this.
